sudo: required #is required to use docker service in travis

language: java

services:
  - docker # required, but travis uses older version of docker :(

install:
  - ./mvnw clean install dockerfile:build

script:
  - ./mvnw clean verify

after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  # - docker build -t my_example_app .
  - docker tag hackslot/slot-machine:latest 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine
  - docker push 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine:latest