language: java
install:
- "./mvnw clean install -DskipTests"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ufxD+HjBdg41KconiZXzYJRH/J5BHBMUphE9oTDzbFFhcOX3Lma1N9rIRyQo9mK2uWPbPwVOqRsyi3//n1iCTDY2kPr10X2BYpDdT06pLPqjjr/a+2AM3u7vHUIH/s9wdR3tS2Hss+jX/bmI93i6MrwrvyGNHOkdNViun9dtp3ILV/pseMFj5Akps7VGXdmNAYA/408QDuk/vm9LF+c7xXhaJhyqM2k6HnqaTAiuPsOamjEwnOVclq8S2XcXLrjCLAqdL/SFlK3rMgjCo8mF2TmZWVk+iAFjl5IA2ChlHkdHI2xhj1oYV7mSesOGyWpkozy+7ZeADUagoy9N4/96ZmHFUWhfRxulGjXTradAsxhBP7Ih4S543qi9exY703GA0E7IH+fH2pEH6sT5s0XMur5HxSLcfAQBYSIyvw8fjJa0gL1tvK2vIiYMsyPyjFX1UPVtIsldqlHuLyV1bQW0ZERfIBz84FGchzgZaGXshYdTgVsy8C2F4RBgmSp23zxPNuOtQ4phZlp+H8VDdfpcJjkdwLn9aW5TLzaHZuNboU5ZMEBpI+uFVGuN4z7JoNlWAc7UKgp6v0E6oRq+xQizkFbCkAhi+sOVXqn5DmkqIlb0kJRguBAhVF89lEKRuKxme5y85ECvquCtmNm7W1LKx89Y86h2yfXRVKEQ2bv0Q2g=
  app: hackslot-slotmachine
  on:
    repo: skows-l24/slotmachine
    branch: reactive
notifications:
  hipchat:
    rooms:
      secure: nAJbGZ8iLR/vxyZhm8NyMax9xuptYrD5b3nxrev2QZHpgti+AE+k4Cf03BFLYtoDkxwZy55pHhfTyTNPotqAos7YtKKIwglXL99/Nu0YRooClSsk58Q5RbjXirqh19K9CcScQdY+CgdSpSIIpwzY8EuZbe1thhrRWyrzjr87KedqwkYTbDP/FqD1Q5woebeMIhENqnliW5jKc3zAjP5jUxEs1pc+1/fAuprO1hinWxOJRyyeodDk9urFMeNjOZd9nf4KtqZBgPoDFhIh3g3Xs8Qh1U4Z1XxTtFR4UaMVW8iDVPchwWGRs6ZzH6OwZxn3OowrGRZLum5Xo0tSN7OnDa13p+I22VxIQAXxK3h7WsN1NKEXPpN7TShNnus/UBR6o8jpPjtbbRDezq/eFDEaP6G5EwwgoiaHjuptCZobKUZ3rs0hKNlOdkT2gJyh7okqJstghE/v3CjF3N3e70ENB6yTqOxoFs8Fr1MT6BXLPsbJJFKAk9eOHTu+ww+eejcy9fxB+cOfpMo2qjrVX/xeeLNodg+xpjI87eWdwG3rd70/7SPpfJMu99VQGnmM8cxG+TTOF2dDo5Ab452rqyKuETn+nygY6Vbbmne6O0vr9Md+I02O46GW51DTOtUYP2zBLAPwBmiBu8ziQYaWFzNlSsqzcsbBdIRMC7YXcNdCND4=
