sudo: required
language: java
services:
- docker
install:
- "./mvnw clean install dockerfile:build"
script:
- "./mvnw clean verify"
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region us-east-1)
- docker tag hackslot/slot-machine:latest 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine
- docker push 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine:latest
env:
  global:
  - secure: D2JGy2A1cCYbQmh5lIlKJby3N0kXKzhi9PBEkKs9ji0fMqV4qwtzOd9EOJVohMzrV7aY2TnrRiyecOwjKzbromqIVzcTvCunckXXHtIzt5fh4Iy/betD2kDdBLrxnb74Tx0PwlIpgqlJ8B8xcGIOqTDQ84ywDqC/LxKPO5XbMJXSyHw1eEjGdXj8ZDQ0+NZwMgAS5ap+Tq67PcCARAbkupmM1EvrEa2cNP7wGDji/oaREHkdipNF5soHWGPMkHSOmo8KR1DV8oPD3oUD+lHd8qbObma2e8i05cq7vcHQrqj7Mz0/iK5K5hbYpDu39MWHnO1HDd0EXlR/FHBh9JyFYImBfo8ECEWqdoeUSQVbrxUPfjuKBeTGBs4YPf4KK+nk/rleNXRrQlJ6tVGB7d7TJ4DjBmjvUW9zguUjlVsu/QXrz4592my7GtRr4ZTPUAdZLM+JlVOLic6GxIn8WGa0rHw6MFCYnth7cKUACerJ4mfndqWGyUOYtC7OAdf9tY42LezW2/GFkwyNe31592XGyYYe6HFJiVf9hR6RJnsTRBQOdzl1iA4yWT5LToCcex84td4Jack97BIxKxOpElK5ejC//HVzVHPkEp8Gbd9yQvM1KhmhAvQscm8kaeW9u9DQ+WIDRrKhyoQhDpByNK8Zc516BjO6YBYrNxp/tjvl0sg=
  - secure: yy/kFBeMoSKl0GFhCarIC5Rp6s8NTXWbEH9RfGPxR5KLzb1VZybGER0CfX/RNxxgYzASCxaERSFef00Y3M/ulNoqnQAQWZPjyGQvhGLScs+Bx7onF3FXdT+pCbx0Wl8yoMglZwbEaoMEwO7jThLVd7Hvc6NB2xJI8L2Q0h6YWfItPoVx3zNgiXB2bWFIFx6krcQi08wS0OCI5nNPo4nwJSLbIc0bsw+v24+1DfHpUZE9686E43VC8UGuI4hbU2zoAOU9xpFHTDD7MeME9Ev//JyQUHsOSINswJsPIxhN5nLv/ymMdSbOIaMypa5Nebg+hAlrtjY+oKw+DMvc11MKUwvgbt2d1DT2TMUIm8ZU00QuRCK4390Tic1UxTdUs93WdqXTUFTTANRqiwEMcAt4PLuCKYgK7FVNjUgtFl6bMKpJW9cS03tK9/viLaHq9aYsrjURnoPwAWklpOmMGda9fprplEdHAlS0sOJYAa/uH9Dex7bEyDvGFjl109rhaAMBD9pygQQXpaDaroEYJL95FXQH1LV/5gcgBM7qaEontfRhsegQrczqRyRveawgEWBUUikRQ0lL6Mui82tGn/keXYCxPVaHwolkc20+FbQJ1142Vih2IorY1c/s4/f5sg/BrtQnaGii5Yyqo/cR/VUWABofBSsUTFWpkTsLoaZnDw4=
