sudo: required
language: java
services:
- docker
install:
- "./mvnw clean install dockerfile:build -DskipTests"
deploy:
  provider: heroku
  api_key:
    secure: ufxD+HjBdg41KconiZXzYJRH/J5BHBMUphE9oTDzbFFhcOX3Lma1N9rIRyQo9mK2uWPbPwVOqRsyi3//n1iCTDY2kPr10X2BYpDdT06pLPqjjr/a+2AM3u7vHUIH/s9wdR3tS2Hss+jX/bmI93i6MrwrvyGNHOkdNViun9dtp3ILV/pseMFj5Akps7VGXdmNAYA/408QDuk/vm9LF+c7xXhaJhyqM2k6HnqaTAiuPsOamjEwnOVclq8S2XcXLrjCLAqdL/SFlK3rMgjCo8mF2TmZWVk+iAFjl5IA2ChlHkdHI2xhj1oYV7mSesOGyWpkozy+7ZeADUagoy9N4/96ZmHFUWhfRxulGjXTradAsxhBP7Ih4S543qi9exY703GA0E7IH+fH2pEH6sT5s0XMur5HxSLcfAQBYSIyvw8fjJa0gL1tvK2vIiYMsyPyjFX1UPVtIsldqlHuLyV1bQW0ZERfIBz84FGchzgZaGXshYdTgVsy8C2F4RBgmSp23zxPNuOtQ4phZlp+H8VDdfpcJjkdwLn9aW5TLzaHZuNboU5ZMEBpI+uFVGuN4z7JoNlWAc7UKgp6v0E6oRq+xQizkFbCkAhi+sOVXqn5DmkqIlb0kJRguBAhVF89lEKRuKxme5y85ECvquCtmNm7W1LKx89Y86h2yfXRVKEQ2bv0Q2g=
  app: slotmachine
  on:
    repo: skows-l24/slotmachine
    branch: docker-aws-testing
