sudo: required
language: java
services:
- docker
install:
- "./mvnw clean install dockerfile:build"
script:
- "./mvnw clean verify"
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region us-east-1)
- docker tag hackslot/slot-machine:greatest 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine
- docker push 758649603159.dkr.ecr.us-east-2.amazonaws.com/slotmachine:greatest
env:
  global:
  - secure: yy/kFBeMoSKl0GFhCarIC5Rp6s8NTXWbEH9RfGPxR5KLzb1VZybGER0CfX/RNxxgYzASCxaERSFef00Y3M/ulNoqnQAQWZPjyGQvhGLScs+Bx7onF3FXdT+pCbx0Wl8yoMglZwbEaoMEwO7jThLVd7Hvc6NB2xJI8L2Q0h6YWfItPoVx3zNgiXB2bWFIFx6krcQi08wS0OCI5nNPo4nwJSLbIc0bsw+v24+1DfHpUZE9686E43VC8UGuI4hbU2zoAOU9xpFHTDD7MeME9Ev//JyQUHsOSINswJsPIxhN5nLv/ymMdSbOIaMypa5Nebg+hAlrtjY+oKw+DMvc11MKUwvgbt2d1DT2TMUIm8ZU00QuRCK4390Tic1UxTdUs93WdqXTUFTTANRqiwEMcAt4PLuCKYgK7FVNjUgtFl6bMKpJW9cS03tK9/viLaHq9aYsrjURnoPwAWklpOmMGda9fprplEdHAlS0sOJYAa/uH9Dex7bEyDvGFjl109rhaAMBD9pygQQXpaDaroEYJL95FXQH1LV/5gcgBM7qaEontfRhsegQrczqRyRveawgEWBUUikRQ0lL6Mui82tGn/keXYCxPVaHwolkc20+FbQJ1142Vih2IorY1c/s4/f5sg/BrtQnaGii5Yyqo/cR/VUWABofBSsUTFWpkTsLoaZnDw4=
  - secure: EHs1JK8dgNOdiemsPJk3oDjPAaoTy2kE73iENqcJlVZ6TJYpcnxnFC/Jb890QMUnEBuUKUDFMNCSC5ajmzee1KtT3MPFO/KY4HWr0h53ra8KHfTf4TUyAMPdAcb5K6lPcNUFFFmJzKS2v4CxHC6RjkRRrhntvYAS3aQ5CLSUjJbNHIZfk3K7cPKOEFlQXUK4oel+cdk8F7Lq2iPlsoCS8FNhVi/QLOgqBopMTqADHfdP3TUexksNbJd6CW8c4xajttR9BIF8YHO0828hCTswGmNTwo/ep6NzgP4tmFYuzNQkImAWB1oUBmv2rM51y5nZvXlGF2BspCv7hXY5K83k4+/m0X7BOR47AVgPysGHFHM0hdMuiFNbnqXT5tGCgT/s7201uL8SKRwlZBQfgF+xqYgm7pF83261sVqHzmNDhES22vtEkSpDo3AWMocLDc5ZOxxTsMfRdCUTMxolfHMbBUQfrLKkU356gxRI6MnY1HypgLHnSKnRwvPxiE9er32m/UXlVAn5aBL0/w3EPxSCgqI1QpCJbbabXkdMVfTKQtK8lDpNNV/W622qGPMoAUNCwdUf8lBiSmoVex0JFgcgSiO2jRFjSlFiJf/pIiBjq48mU/4D7CSyMKm8ZTWxsM/dJFdkB7VSJBWvWbhGVgddLPOJBvguEJ2sd25lByJ4zxI=
