server:
  port: 24908
spring:
  application:
    name: slot-machine
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
application:
  swagger:
    title: Slot Machine
    description: Here you see the awesome Slot Machine with all its open interfaces
